### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by ZimbiX** [grosser/parallel_split_test#17]
Hey, thanks for your work on this and parallel_tests!

Would it be possible to add support for JRuby?

I see `Process.fork is not supported by this Ruby` when I try to run my tests after switching to JRuby.

Your Parallel gem which this uses, [is where the message comes from](https://github.com/grosser/parallel/blob/88c75b70480c5735463c47b4048ec36711a90902/lib/parallel.rb#L248).

I can think of three options:

- Using threads, which Parallel already supports (less isolated)
- Launching a new process for each example instead of forking (slower)
- Add support to parallel_tests for running examples separately

**Comment by grosser** [comment]
Threads sounds simple and straightforward ... might even work with dbs when using transactions, but lots of other things will fail.
New processes might work, but require a fair bit or architecture I'd imagine (they need to share a queue via a file or so).
Parallel-tests might work with separate example, I think it definitely works with cucumbers, but it cannot equalize runtimes since it spawns separate processes.

**Comment by sorenessen** [comment]
I see that parallel_tests gem hasn't had support for JRuby ever. Finding articles back to 2013 but haven't seen any updates since. Is this just a pipedream-not gonna happen? I'm not sure how to configure parallel tests with jruby otherwise. Is there a good resource anybody can recommend for any of the alternatives mentioned above? Jruby documentation for this seems to be scarce or I'm just not looking hard enough.

**Comment by grosser** [comment]
parallel_tests works with jruby https://github.com/grosser/parallel_tests/blob/master/.github/workflows/test.yml#L16 you are talking about parallel_split_test right ?

An easy fix for parallel_split_test would be to change https://github.com/grosser/parallel_split_test/blob/master/lib/parallel_split_test/command_line.rb#L23 to use in_threads ... that might give a decent boost and not require a rewrite.

**Comment by sorenessen** [comment]
hmm, sorry this will be off topic, but other members of my team as well as myself, after installing the parallel_tests gem and configuring the database.yml and then running `rails parallel:create` we receive an output like:
```You have requested:
  activerecord-jdbcmysql-adapter ~> 52.6

The bundle currently has activerecord-jdbcmysql-adapter locked at 52.6.
Try running `bundle update activerecord-jdbcmysql-adapter`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Run `bundle install` to install missing gems.
```
Changing versions or following the output instructions always yields the same result.

**Comment by grosser** [comment]
moving discussion here then https://github.com/grosser/parallel_tests/issues/783
